app <- ShinyDriver$new("../")
app$snapshotInit("heatmap_colors_etc")

app$setInputs(example_data = TRUE)
app$setInputs(main = "Plot")
app$setInputs(plotselect = "heatmap")
app$setInputs(settings = "Labeling and colour(s)")
app$setInputs(title = "Heatmap Test")
app$setInputs(xlab = "x test")
app$setInputs(ylab = "y test")
app$setInputs(rotate_labels = TRUE)
app$setInputs(xgrid = "major")
app$setInputs(ygrid = "none")
app$setInputs(col1 = "#FFC9C9")
app$setInputs(col2 = "#FF0000")
app$setInputs(settings = "Reference Line")
app$setInputs(draw_ref_line = TRUE)
app$setInputs(ref_line = "hline")
app$setInputs(interc = 0.9)
app$setInputs(refsize = 0.9)
app$setInputs(refcol = "#FF0000")
app$snapshot()
