app <- ShinyDriver$new("../")
app$snapshotInit("histo_colors_etc")

app$setInputs(example_data = TRUE)
app$setInputs(main = "Plot")
app$setInputs(plotselect = "histogram")
app$setInputs(settings = "Labeling and colour(s)")
app$setInputs(title = "")
app$setInputs(title = "Histo ")
app$setInputs(title = "Histo Test")
app$setInputs(xlab = "x test")
app$setInputs(ylab = "y test")
app$setInputs(rotate_labels = TRUE)
app$setInputs(xgrid = "major")
app$setInputs(ygrid = "none")
app$setInputs(col1 = "#FF0000")
app$setInputs(col2 = "#0011FF")
app$setInputs(settings = "Reference Line")
app$setInputs(draw_ref_line = TRUE)
app$setInputs(ref_line = "hline")
app$setInputs(interc = 1)
app$setInputs(interc = 2)
app$setInputs(interc = 3)
app$setInputs(interc = 4)
app$setInputs(interc = 5)
app$setInputs(interc = 208)
app$setInputs(refsize = 1.1)
app$setInputs(refcol = "#00FF40")
app$setInputs(ref_linetype = "longdash")
app$setInputs(ref_linetype = "dotdash")
app$snapshot()
