app <- ShinyDriver$new("../")
app$snapshotInit("line_group_by")

app$setInputs(example_data = TRUE)
app$setInputs(main = "Plot")
app$setInputs(plotselect = "line")
app$setInputs(y = "price")
app$setInputs(group = "color")
app$setInputs(group = "cut")
app$snapshot()
