app <- ShinyDriver$new("../")
app$snapshotInit("scatter_colors_etc")

app$setInputs(example_data = TRUE)
app$setInputs(main = "Plot")
app$setInputs(settings = "Labeling and colour(s)")
app$setInputs(title = "Scatter Test")
app$setInputs(xlab = "x ")
app$setInputs(xlab = "x test")
app$setInputs(ylab = "y test")
app$setInputs(rotate_labels = TRUE)
app$setInputs(xgrid = "major")
app$setInputs(ygrid = "none")
app$setInputs(col1 = "#FF0000")
app$setInputs(settings = "Reference Line")
app$setInputs(ref_line = "hline")
app$setInputs(interc = 0.9)
app$setInputs(refcol = "#F20000")
app$setInputs(draw_ref_line = TRUE)
app$snapshot()
